Convert MagicRender to Kotlin. Calling code throws NoSuchMethodError :(
Tested with Seeker, even though the method sig is the same, having it as Kotlin seems to require a recompile to use. Maybe diff primitives?